/**
 * Extensible audit action registry (spec #41). This is a growing enum, not
 * a hard-coded handful — add new string constants here as new auditable
 * actions are introduced; never write raw strings at call sites.
 */
export const AUDIT_ACTIONS = {
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  USER_CREATED: "USER_CREATED",
  USER_DISABLED: "USER_DISABLED",
  USER_ENABLED: "USER_ENABLED",
  USER_PASSWORD_RESET: "USER_PASSWORD_RESET",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",

  MENU_CREATED: "MENU_CREATED",
  MENU_UPDATED: "MENU_UPDATED",
  MENU_PRICE_CHANGED: "MENU_PRICE_CHANGED",
  MENU_DELETED: "MENU_DELETED",
  CATEGORY_DELETED: "CATEGORY_DELETED",
  ITEM_UNAVAILABLE: "ITEM_UNAVAILABLE",
  ITEM_AVAILABLE: "ITEM_AVAILABLE",

  OFFER_CREATED: "OFFER_CREATED",
  OFFER_UPDATED: "OFFER_UPDATED",
  OFFER_DELETED: "OFFER_DELETED",
  COMBO_CREATED: "COMBO_CREATED",
  COMBO_UPDATED: "COMBO_UPDATED",
  COMBO_DELETED: "COMBO_DELETED",
  DISCOUNT_APPLIED: "DISCOUNT_APPLIED",

  TABLE_CREATED: "TABLE_CREATED",
  TABLE_UPDATED: "TABLE_UPDATED",
  TABLE_STATUS_CHANGED: "TABLE_STATUS_CHANGED",

  ORDER_CREATED: "ORDER_CREATED",
  ORDER_MODIFIED: "ORDER_MODIFIED",
  ORDER_SENT_TO_KITCHEN: "ORDER_SENT_TO_KITCHEN",
  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_VOIDED: "ORDER_VOIDED",

  BILL_CREATED: "BILL_CREATED",
  BILL_VOIDED: "BILL_VOIDED",
  PAYMENT_CREATED: "PAYMENT_CREATED",
  PAYMENT_VOIDED: "PAYMENT_VOIDED",

  RESTAURANT_UPDATED: "RESTAURANT_UPDATED",
  CRITICAL_SETTING_CHANGED: "CRITICAL_SETTING_CHANGED",
  DATABASE_EXPORTED: "DATABASE_EXPORTED",
  DATABASE_RESTORED: "DATABASE_RESTORED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
